apl_descriptions = {
    "<-": "Assignment",
    "xx": "Direction | Times",
    ":-": "Reciprocal | Divide",
    "*O": "Natural logarithm | Logarithm",
    "OO": "Pi Times | Circular",
    "|_": "Decode (Dyadic)",
    "TT": "Encode (Dyadic)",
    "-|": "Same | Left",
    "|-": "Same | Right",
    "=/": "Unique Mask | Not equal",
    "<_": "Less than or equal to (Dyadic)",
    ">_": "Greater than or equal to (Dyadic)",
    "==": "Depth | Match",
    "_=": "Depth | Match",
    "vv": "Or (Dyadic)",
    "^^": "And (Dyadic)",
    "^~": "Nan (Dyadic)",
    "v~": "Nor (Dyadic)",
    "^|": "Mix | Take",
    "v|": "Split | Drop",
    "cc": "Enclose | Partitioned enclose",
    "))": "First | Pick",
    "c_": "Nest | Partition",
    "A|": "Grade up | Grade up",
    "V|": "Grade down | Grade down",
    "ii": "Indices | Indices of",
    "i_": "Where | Interval index",
    "ee": "Enlist | Member of",
    "e_": "Find (Dyadic)",
    "uu": "Unique | Union",
    "nn": "Intersection (Dyadic)",
    "/-": "Replicate First | Reduce First",
    "\\-": "Expand First | Scan First",
    ",-": "Table | Catenate First",
    "O-": "Reverse First | Rotate First",
    "O\\": "Transpose | Reorder Axes",
    "~:": "Constant/Commute | Self/Swap",
    "*:": "Repeat (Dyadic)",
    "oo": "Curry/Compose | Beside/Bind",
    "o:": "Rank/Atop (Dyadic)",
    "O:": "Over (Dyadic)",
    "[]": "SYSTEM",
    "o_": "Execute",
    "o-": "Format",
    "To": "Format",
    "<>": "Statement separator",
    "on": "Comment",
    "ww": "Right argument | Right operand",
    "aa": "Left argument | Left operand",
    "VV": "Recursion | Recursion",
    "--": "Negative",
    "0~": "Empty numeric vector",
    "[-": "Matrix inverse | Matrix divide",
    "-]": "Matrix inverse | Matrix divide",
    "[|": "Index",
    "|]": "Index",
    "7=": "Tally | Not match",
    "Z-": "Tally | Not match",
    "77": "Ceiling | Maximum",
    "FF": "Ceiling | Maximum",
    "ll": "Floor | Minimum",
    "LL": "Floor | Minimum",
    "::": "Each",
    "\"\"": "Each",
    "rr": "Shape | Reshape",
    "pp": "Shape | Reshape",
    "[:": "Variant",
    ":]": "Variant",
    "[=": "Index key | Key",
    "=]": "Index key | Key",
    "[<": "Stencil",
    ">]": "Stencil",
    "T_": "I-beam",
    "II": "I-beam",
}